Repository lsd-rs/lsd, pull requests merged in 2023-11, with the labels that each got.

#944 ⬆️ bump lscolors to v0.15.0 and msrv to 1.69.0
  .github/workflows/CICD.yml
  Cargo.lock
  Cargo.toml
  build.rs
  src/meta/mod.rs
  src/sort.rs
  tests/integration.rs
Labels: size/S

#929 Adding some more icons for filenames and extensions
  src/theme/icon.rs
Labels: size/L

#945 Add PRQL
  src/theme/icon.rs
Labels: size/XS

#946 Update icon.rs
  src/theme/icon.rs
Labels: size/XS

#935 Fix `literal` flag not being recognized from config file
  src/flags/literal.rs
Labels: size/S

#957 Update README: Icon Theme config does not require build from source
  README.md
Labels: size/XS

#920 installation: windows (winget) (README)
  README.md
Labels: size/XS

#960 :memo: docs: add notice for the readme is for dev
  README.md
Labels: size/XS

#901 RPM spec file for lsd
  lsd.spec
Labels: size/M

#961 Updated README.md to contain clear instructions for color scheming in Windows
  README.md
Labels: size/XS

#953 ci: Release PowerShell completion script
  .github/workflows/CICD.yml
Labels: size/XS
