Repository lsd-rs/lsd, pull requests merged in 2023-09, with the labels that each got.

#907 Add changelog deprecation notice
  .github/PULL_REQUEST_TEMPLATE
  CHANGELOG.md
Labels: size/XS

#909 add `obj` directory icon
  src/theme/icon.rs
Labels: size/XS

#913 upgrade dirs to version 5
  Cargo.lock
  Cargo.toml
Labels: size/M

#914 upgrade lscolors to 0.14.0
  Cargo.lock
  Cargo.toml
Labels: size/S

#915 :heart: update funding to Wei
  .github/FUNDING.yml
Labels: size/XS

#916 :arrow_down: change dirs to 4
  Cargo.lock
  Cargo.toml
Labels: size/M
