Repository lsd-rs/lsd, pull requests merged in 2024-02, with the labels that each got.

#985 📝 document `--date=locale`
  README.md
  doc/lsd.md
  src/app.rs
  src/config_file.rs
  src/flags/date.rs
Labels: size/S

#984 update various dependencies
  Cargo.lock
  Cargo.toml
  src/display.rs
  src/flags.rs
  src/meta/mod.rs
Labels: size/XXL

#983 :hammer: :art: put fish auto comp under vendor dir
  .github/workflows/CICD.yml
Labels: size/XS

#993 change neovim to proper icon
  src/theme/icon.rs
Labels: size/XS

#992 Add fennel support
  src/theme/icon.rs
Labels: size/XS
