Repository lsd-rs/lsd, pull requests merged in 2024-03, with the labels that each got.

#1007 Add icons for .apng and .avif
  src/theme/icon.rs
Labels: size/XS

#1015 :tada: release v1.1.1
  CHANGELOG.md
  CODEOWNERS
  Cargo.lock
  Cargo.toml
  OWNERS
  README.md
  lsd.spec
Labels: size/L

#1021 chore: update Cargo.lock for latest version
  Cargo.lock
Labels: lgtm, size/XS, approved

#1022 chore: build with `--locked` flag in CI
  .github/workflows/CICD.yml
Labels: size/XS
