Repository lsd-rs/lsd, pull requests merged in 2024-08, with the labels that each got.

#1084 Update current release
  README.md
Labels: size/XS

#1020 :tada: release v1.1.3
  Cargo.lock
  Cargo.toml
  lsd.spec
Labels: size/XS, approved

#1087 Revert ":tada: release v1.1.4"
  Cargo.lock
  Cargo.toml
  README.md
  lsd.spec
Labels: approved

#1050 add subtitle/closed caption icons
  src/theme/icon.rs
Labels: size/XS
