Repository lsd-rs/lsd, pull requests merged in 2024-04, with the labels that each got.

#1025 Update permission options in README; minor tweaks
  README.md
Labels: size/S

#1037 :heart: update warp logo with linux support
  README.md
Labels: size/S, approved

#1026 :hammer: :tada: use cache for user and group in unix, gain 60% improve
  Cargo.lock
  src/display.rs
  src/meta/mod.rs
  src/meta/name.rs
  src/meta/owner.rs
Labels: size/L

#1038 add blender icons
  src/theme/icon.rs
Labels: size/XS
